server:
  port: 8090
logging:
  level: DEBUG
spring:
  profiles: 
    active: '@profileActive@'
  messages:
    basename: message/resource,message/lookup
    cache-seconds: ${args.messages.cache-seconds:5}
security:
  oauth2:
    client: 
      client-id: test
      client-secret: testsec
    resource:
      id: account
      user-info-uri: http://localhost:8091/oauth/token
      token-info-uri: http://localhost:8091/oauth/check_token
#  datasource:
#    url: ${args.datasource.url:jdbc:mysql://localhost:8099/yqyl_business?characterEncoding=utf-8&serverTimezone=UTC }
#    username: ${args.datasource.username:dev}
#    password: ${args.datasource.password:!QAZ2wsx}
#    driverClassName: com.mysql.cj.jdbc.Driver
#    testWhileIdle: true
#    validationQuery: select 1
#    sqlScriptEncoding: utf-8
#  jpa:
#    database: MYSQL
#    show-sql: false
#    hibernate:
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      use-new-id-generator-mappings: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

---
spring: 
  profiles: dev
#args:
#  datasource: 
#    url: jdbc:mysql://localhost:3306/yqyl_business?characterEncoding=utf-8&serverTimezone=UTC
     
---
spring: 
  profiles: qa
args:
  messages: 
    cache-seconds: -1
#  datasource: 
#    url: jdbc:mysql://localhost:8099/yqyl_business?characterEncoding=utf-8&serverTimezone=UTC
    